* Guix
** TODO Implement hybernate
** Audio
create a service for pulseaudio
* Emacs
enable lexical scope in org source buffers since that's where most
evaluation happens

eshell-at helm interface that has a separate source for existing
buffers (which has an alternate binding for opening a new eshell in
the directory of that existing buffer) placed above a filesystem
searching source.
** TODO enable which-key-mode in god-mode
** language tools
- Add Rust editing tools
- add subleader for inspect (as opposed to eval)
** projects
*** Projectile
- Add flycheck file and #autosave# or whatever file to projectile
  exclusions !!!!!!
*** Skeletor
- contribute the subdirectory feature, ~:subdir~ keyword.
- Make a completion source that uses nix packages list to select packages for a project.
- project skeletons set up for
  - Generic project with Nix and direnv (choose directory manually) DONE
  - Common Lisp DONE
  - C
  - C++
  - Rust
  - Prolog
** COMMENT Launcher
I want the following features:
Simple macro to create launcher shortcuts
example usage:
#+BEGIN_SRC emacs-lisp
  (launcher-shortcuts
   firefox
   krita
   gimp
   (spotify :args "--force-device-scale-factor=2"
            :switch-to t)
   (wifi :shell-command "cool-retro-term"
         :args "-e nmtui"
         :switch-to t)
   (bluetooth :shell-command "blueman-manager"
              :before (lambda ()
                        (split-window-vertically)
                        (other-window 1))
              :switch-to t))
#+END_SRC

or add shortcuts manually like
#+BEGIN_SRC emacs-lisp
  (defun launcher/firefox
      (start-process-shell-command "firefox" nil "firefox"))
#+END_SRC

shortcuts are just defuns under ~launcher/~, the launch function simply
narrows the launch functions. Keep what metadata you need.

this is a good starting point, but eventually I want to parse .desktop
files to add shortcuts automatically. I can continue to add launcher
features over time in order to compete with those fancy gui launchers.
I imagine that it will become useful to others, so why not make a package?

The .desktop parser just outputs launch functions AKA shortcuts whose
properties can be overriden by ~launcher-shortcuts~.
** COMMENT Qutebrowser
I want qutebrowser and exwm buffers to be part of the same helm source
in helm-mini, but the default display for helm buffers hangs for
absurdly long URLs in the qutebrowser buffer's title. You need to make
a source patch to helm-mini to fix this. Look at helm-exwm and
helm-qutebrowser for inspiration.
**  EXWM
Set default-directory of exwm buffers (mpv)

*** COMMENT randr
Some way to minimize exwm's "fullscreen" windows.  Easiest way is to
just correct xrandr when switching from a fullscreen'd workspace.

** ERC
*** Bitlbee
helm interface for joining discord channel, or at least an interface
organized by server

twitter shortened links replaced with expanded forms in buffer (request.el)
* Other
⠀⠀⠀⣴⣴⡤
⠀⣠⠀⢿⠇⡇⠀⠀⠀⠀⠀⠀⠀⢰⢷⡗
⠀⢶⢽⠿⣗⠀⠀⠀⠀⠀⠀⠀⠀⣼⡧⠂⠀⠀⣼⣷⡆
⠀⠀⣾⢶⠐⣱⠀⠀⠀⠀⠀⣤⣜⣻⣧⣲⣦⠤⣧⣿⠶
⠀⢀⣿⣿⣇⠀⠀⠀⠀⠀⠀⠛⠿⣿⣿⣷⣤⣄⡹⣿⣷
⠀⢸⣿⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⢿⣿⣿⣿⣿⣿
⠀⠿⠃⠈⠿⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⠿⠿⠿

⠀⢀⢀⡀⠀⢀⣤⠀⠀⠀⠀⠀⠀⠀⡀⡀
⠀⣿⡟⡇⠀⠭⡋⠅⠀⠀⠀⠀⠀⢰⣟⢿
⠀⣹⡌⠀⠀⣨⣾⣷⣄⠀⠀⠀⠀⢈⠔⠌
⠰⣷⣿⡀⢐⢿⣿⣿⢻⠀⠀⠀⢠⣿⡿⡤⣴⠄⢀⣀⡀
⠘⣿⣿⠂⠈⢸⣿⣿⣸⠀⠀⠀⢘⣿⣿⣀⡠⣠⣺⣿⣷
⠀⣿⣿⡆⠀⢸⣿⣿⣾⡇⠀⣿⣿⣿⣿⣿⣗⣻⡻⠿⠁
⠀⣿⣿⡇⠀⢸⣿⣿⡇⠀⠀⠉⠉⠉⠉⠉⠉⠁
