alias e="emacsclient --create-frame"
alias edw="emacs-daemon-workspace"
alias nixconf="emacsclient --create-frame -e '(find-file \"/sudo::/etc/nixos/configuration.nix\")'"
alias econf="emacsclient --create-frame ~/.emacs"
alias md="mkdir"
alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias spdep="spark deploy ~/.dotfiles/dotfiles.sus"
alias nrs="sudo nixos-rebuild switch"
alias nget="sudo nix-env -i "
alias qlrun="rlwrap quicklisp run"
alias shen="rlwrap /home/adrian/code/common-lisp/my-forks/shen-cl/bin/sbcl/shen -l ~/.shen-cl.shen"
alias ns="nix-shell"
alias ":q"="exit"
alias spotify="spotify --force-device-scale-factor=2.0 > out.log 2> /dev/null &"
alias def="~/auto/def/def.bash"
